name: Artificial Intelligence - Generative Artificial Intelligence - Tool - Deployment Tool
type: Tech-3
data:
  labels:
    - ':projects/vllm'
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 674187265
          name: AmineDiro/cria
        - id: 634081686
          name: mlc-ai/mlc-llm
        - id: 630249429
          name: lamini-ai/lamini
