name: Grafana Mimir
type: Project
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 385634291
          name: grafana/mimir
        - id: 393288578
          name: grafana/mimir-prometheus
        - id: 487001991
          name: grafana/mimir-proxies
