name: Cloud Native - Provisioning - Automation & Configuration
type: Tech-2
data:
  labels:
    - ':companies/alibaba/openyurt'
    - ':companies/capitalone/cloud_custodian'
    - ':companies/huawei/kubeedge'
    - ':companies/redhat/metal3'
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 144783430
          name: airshipit/treasuremap
        - id: 302703576
          name: project-akri/akri
        - id: 3638964
          name: ansible/ansible
        - id: 53127403
          name: apolloconfig/apollo
        - id: 3910314
          name: cloudfoundry/bosh
        - id: 82700090
          name: uber/cadence
        - id: 105809298
          name: cdk8s-team/cdk8s
        - id: 3543548
          name: cfengine/core
        - id: 108278
          name: chef/chef
        - id: 18326574
          name: cloudify-cosmo/cloudify-manager
        - id: 288523518
          name: couler-proj/couler
        - id: 415188495
          name: devstream-io/devstream
        - id: 199487892
          name: digitalrebar/provision
        - id: 258750
          name: theforeman/foreman
        - id: 20445947
          name: juju/juju
        - id: 238232099
          name: loft-sh/kiosk
        - id: 227010082
          name: kubedl-io/kubedl
        - id: 332999480
          name: kubefirst/kubefirst
        - id: 516603039
          name: kubewharf/kubezoo
        - id: 488866928
          name: KusionStack/kusion
        - id: 46932243
          name: linuxkit/linuxkit
        - id: 86509608
          name: maas/maas
        - id: 20789757
          name: ManageIQ/manageiq
        - id: 5874515
          name: mistio/mist-ce
        - id: 13839311
          name: openstack/openstack
        - id: 72477752
          name: pulumi/pulumi
        - id: 910744
          name: puppetlabs/puppet
        - id: 886774
          name: rundeck/rundeck
        - id: 1390248
          name: saltstack/salt
        - id: 19051806
          name: stackstorm/st2
        - id: 322759957
          name: superedge/superedge
        - id: 17728164
          name: hashicorp/terraform
        - id: 215102779
          name: tinkerbell/tink
