name: Docker
type: Company
data:
  labels:
    - containerd
  platforms:
    - name: GitHub
      type: Code Hosting
      orgs:
        - id: 5429470
          name: docker
        - id: 27259197
          name: moby
