name: publish

on:
  push:
    branches: [ master ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node 14 env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Test
        env:
          CLIKCKHOUSE_QUERY_URL: ${{ secrets.CLIKCKHOUSE_QUERY_URL }}
        run: |
          npm install
          npm run publish

      - name: Update to oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          asset-path: ./dist
          target-path: ${{ secrets.OSS_TARGET_PATH }}
